# Generated by Django 6.0.2 on 2026-02-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("age", models.PositiveIntegerField()),
                ("monthly_income", models.PositiveIntegerField()),
                (
                    "approved_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "current_debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("tenure", models.PositiveIntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("emis_paid_on_time", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="loans.customer",
                    ),
                ),
            ],
        ),
    ]
